// Styles for auth components
export const authStyles = {
    container: {
        position: 'fixed',
        top: '20px',
        right: '20px',
        zIndex: 1000,
        color: '#ffffff',
        fontFamily: 'Roboto, sans-serif',
    },
    authButtons: {
        display: 'flex',
        gap: '12px',
    },
    authButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '6px 12px',
        borderRadius: '20px',
        border: '1px solid rgba(255, 255, 255, 0.3)',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        color: '#ffffff',
        fontSize: '14px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    authButtonHover: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderColor: 'rgba(255, 255, 255, 0.5)',
    },
    userInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 12px',
        borderRadius: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        border: '1px solid rgba(255, 255, 255, 0.3)',
    },
    greeting: {
        fontSize: '14px',
        fontWeight: '400',
    },
    userName: {
        fontWeight: '500',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1100,
        backdropFilter: 'blur(3px)',
    },
    modalContent: {
        backgroundColor: '#222222',
        borderRadius: '8px',
        padding: '24px',
        width: '300px',
        position: 'relative',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
    },
    modalTitle: {
        fontSize: '20px',
        marginBottom: '20px',
        color: '#ffffff',
        textAlign: 'center',
    },
    closeButton: {
        position: 'absolute',
        top: '10px',
        right: '10px',
        background: 'none',
        border: 'none',
        color: '#888888',
        cursor: 'pointer',
        padding: '5px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    inputGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    label: {
        fontSize: '14px',
        color: '#cccccc',
    },
    input: {
        padding: '10px',
        borderRadius: '4px',
        backgroundColor: '#333333',
        border: '1px solid #444444',
        color: '#ffffff',
        fontSize: '14px',
    },
    submitButton: {
        padding: '10px',
        backgroundColor: '#4a6c6f',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        marginTop: '10px',
        transition: 'background-color 0.2s',
    },
    submitButtonHover: {
        backgroundColor: '#5a8a8e',
    },
    errorMessage: {
        color: '#ff5555',
        fontSize: '14px',
        textAlign: 'center',
        marginTop: '10px',
    },
    switchText: {
        textAlign: 'center',
        marginTop: '16px',
        fontSize: '14px',
        color: '#bbbbbb',
    },
    switchLink: {
        color: '#80b0b5',
        textDecoration: 'underline',
        cursor: 'pointer',
    }
};