import { TILE_SIZE, TILE_OVERLAP, GRID_SIZE } from '../config.js';

const calcSize = (multiplier = 1) => `${(TILE_SIZE * multiplier)}px`;

export const styles = {
    container: {
        position: 'fixed',
        inset: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'black',
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: `repeat(${GRID_SIZE}, ${calcSize(1)})`,
        gap: 0,
        position: 'relative',
    },
    tile: {
        width: `${TILE_SIZE + TILE_OVERLAP}px`,
        height: `${TILE_SIZE + TILE_OVERLAP}px`,
        margin: `-${TILE_OVERLAP/2}px`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'all 300ms',
        position: 'relative',
        backgroundColor: 'transparent',
        boxSizing: 'border-box',
        zIndex: 20,
    },
    tileLabel: {
        fontFamily: "'Poiret One', sans-serif",
        color: '#E5E5E5',
        fontSize: '0.6rem',
        letterSpacing: '0.1em',
        textTransform: 'uppercase',
        textAlign: 'center',
        padding: '2px 4px',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: '2px',
        pointerEvents: 'none',
        whiteSpace: 'nowrap',
        zIndex: 100,
    },
    activeTile: {
        cursor: 'pointer',
    },
    inactiveTile: {
        cursor: 'default',
    },
    animationOverlay: {
        position: 'absolute',
        pointerEvents: 'none',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    tileAnimation: {
        position: 'absolute',
        zIndex: 22,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    expansionAnimation: {
        width: calcSize(2),
        height: calcSize(2),
        zIndex: 30,
    },
    contractionAnimation: {
        width: calcSize(2),
        height: calcSize(2),
        zIndex: 30,
    },
    backgroundAnimation: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100vw',
        height: '100vh',
        zIndex: 1,
        overflow: 'hidden',
    },
    animationContent: {
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        objectFit: 'cover',
    },
    backgroundContent: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
        objectPosition: 'center',
    },
};